_wandb:
    value:
        cli_version: 0.21.1
        e:
            ls3eql7jthss4fc35t21g69hgaznbn4d:
                codePath: test/test_wandb.py
                codePathLocal: test/test_wandb.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "62343610368"
                email: victor.w.x@icloud.com
                executable: /home/victor/miniconda3/envs/exertion_lvl/bin/python
                git:
                    commit: 29b7eda4ac707592178b96aa2100271ca38192ea
                    remote: git@github.com:VictorWuyueXia/exertion_lvl.git
                gpu: NVIDIA GeForce RTX 4070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070
                      uuid: GPU-b0d12321-bcd8-fdba-631f-e8d2557025ac
                host: Vic-Desktop
                memory:
                    total: "16633729024"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/victor/projects/exertion_lvl/test/test_wandb.py
                python: CPython 3.9.23
                root: /home/victor/projects/exertion_lvl
                startedAt: "2025-08-07T21:01:49.096331Z"
                writerId: ls3eql7jthss4fc35t21g69hgaznbn4d
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.9.23
            "5": 0.21.1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
system:
    value:
        seed: 42
training:
    value:
        batch_size: 4
        epochs: 2
        learning_rate: 0.0001
wandb:
    value:
        description: WandB功能测试
        enabled: true
        monitoring:
            cpu_usage: true
            gpu_interval: 5
            gpu_usage: true
            memory_usage: true
            system_interval: 10
        name: test_run_{timestamp}
        project: exertion-level-detection-test
        tags:
            - test
